version: "3.7"
services:
    server:
        container_name: server
        image: node-server
        build: ./server
        ports:
            - "6969:6969"
        networks:
            - client-backend-network
            - backend-database-network
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            # mounts database files to the local docker filesystem so they persist
            - ./mongo-data:/db
        networks:
            - backend-database-network
    client:
        container_name: client
        image: node-client
        build: ./client
        ports:
            - "3000:3000"
        networks:
            - client-backend-network
networks:
    client-backend-network:
    backend-database-network:
