version: "3.7"
services:
  server:
    container_name: server
    image: node-server
    build: ./server
    networks:
      - frontend
      - backend
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      # mounts database files to the local docker filesystem so they persist 
      - ./data:/data/db
    networks:
      - backend
  client:
    container_name: client
    image: node-client
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
